os: osx
osx_image: xcode11.3
language: objective-c
branches:
  only:
    - master

script:
  xcodebuild -workspace Jared.xcworkspace -scheme JaredTests test ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO